# Variable values to use for deployment
prefix         = "MLP"
aws_region     = "us-east-2"
aws_key        = "jmlayn_aws"
owner_tag      = "jmlayn"
ssh_key        = "~/.ssh/jmlayn_aws"
instance_type  = "m4.large"
azure_location = "eastus2"
nomad_rg       = "jmlayn-nomad"
nomad_storage  = "jmlstorage"
